const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

// Exact 67 products categorized into the 5 final categories
const categorizedProducts = [
  // ----------------------------------------------------
  // CATEGORY 1: Birthday Cakes (25 items)
  // ----------------------------------------------------
  {
    id: "tropical-fruit-n-almond-cake",
    name: "Tropical Fruit N Almond Cake",
    category: "Birthday Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Fresh tropical fruits layered with delicate cream and crunchy toasted almonds.",
    description: "A refreshing celebration cake infused with luscious seasonal fruits, velvety smooth cream, and toasted sliced almonds for the perfect crunch.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Celebration"],
    tags: ["Fruit Cake", "Almond", "Celebration", "Fresh Fruit"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "butterscotch-crunch-cake",
    name: "Butterscotch Crunch Cake",
    category: "Birthday Cakes",
    price: 529,
    originalPrice: 529,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Classic butterscotch layers topped with golden caramelized praline crunch.",
    description: "Rich butterscotch whipped cream sponge crowned with golden butterscotch drops and crunchy praline, perfect for every birthday party.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["Butterscotch", "Praline", "Crunch Cake", "Birthday Special"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "whipped-cream-pineapple-cake",
    name: "Whipped Cream Pineapple Cake",
    category: "Birthday Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Light vanilla sponge infused with juicy pineapples and airy whipped cream.",
    description: "All-time favorite celebratory cake featuring moist vanilla layers generously filled with sweet pineapple chunks and topped with fluffy whipped cream.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Family Gathering", "Celebration"],
    tags: ["Pineapple", "Whipped Cream", "Classic Cake", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "rose-petals-n-pistachio-rasmalai-cake",
    name: "Rose Petals N Pistachio Rasmalai Cake",
    category: "Birthday Cakes",
    price: 699,
    originalPrice: 699,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Royal fusion cake infused with fragrant cardamom rasmalai, pistachios, and dried rose petals.",
    description: "A luxurious Indian fusion dessert cake combining rich saffron-cardamom cream, soaked rasmalai goodness, and garnishes of crunchy pistachios and edible rose petals.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Festival", "Anniversary", "Celebration"],
    tags: ["Rasmalai", "Fusion Cake", "Pistachio", "Rose Petals", "Royal"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "classic-black-forest-cake",
    name: "Classic Black Forest Cake",
    category: "Birthday Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Timeless black forest cake with chocolate shavings and juicy cherry compote.",
    description: "The quintessential celebration cake layered with light chocolate sponge, fluffy vanilla cream, tart cherry filling, and rich dark chocolate flakes.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Party"],
    tags: ["Black Forest", "Cherry", "Classic", "Chocolate Flakes"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "rosy-petals-heart-cake",
    name: "Rosy Petals Heart Cake",
    category: "Birthday Cakes",
    price: 749,
    originalPrice: 749,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Heart-shaped artisanal cake decorated with delicate floral rose accents.",
    description: "An exquisite heart-shaped celebration cake finished with handcrafted rose petal cream piping, created for special moments and birthdays.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Romantic", "Celebration"],
    tags: ["Heart Cake", "Rose Petals", "Romantic", "Designer Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "red-velvet-heart-shape-cake",
    name: "Red Velvet Heart Shape Cake",
    category: "Birthday Cakes",
    price: 799,
    originalPrice: 799,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Striking crimson red velvet heart cake with luscious cream cheese swirl.",
    description: "Moist, velvety crimson sponge sculpted into an elegant heart shape and enveloped in silky cream cheese frosting for unforgettable birthdays.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Valentine", "Special Moments"],
    tags: ["Red Velvet", "Heart Cake", "Cream Cheese", "Premium"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "roses-topped-vanilla-cream-cake",
    name: "Roses Topped Vanilla Cream Cake",
    category: "Birthday Cakes",
    price: 1149,
    originalPrice: 1149,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Grand designer vanilla cream cake crowned with elegant handcrafted floral roses.",
    description: "A showstopping designer cake with delicate vanilla bean sponge, silky buttercream frosting, and artistic floral rose arrangements.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Grand Celebration", "Anniversary"],
    tags: ["Designer Cake", "Vanilla", "Roses", "Grand Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "german-black-forest-cake",
    name: "German Black Forest Cake",
    category: "Birthday Cakes",
    price: 559,
    originalPrice: 559,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Traditional German-style black forest cake with cocoa flakes and tart cherry notes.",
    description: "An authentic German-inspired black forest creation blending dark cocoa sponge, smooth cream layers, and rich chocolate shavings.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["German Black Forest", "Cocoa", "Birthday Cake", "Cherry"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "pink-princess-barbie-cake",
    name: "Pink Princess Barbie Cake",
    category: "Birthday Cakes",
    price: 1479,
    originalPrice: 1479,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Enchanting 3D princess barbie doll cake with pastel pink piped gown.",
    description: "A magical centerpiece for children's birthdays featuring a beautifully detailed Barbie doll centerpiece dressed in swirls of pastel pink whipped cream.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Kids Birthday", "Princess Theme", "Birthday Party"],
    tags: ["Barbie Cake", "Theme Cake", "Kids Birthday", "Pink Princess"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "birthday-photo-cake",
    name: "Birthday Photo Cake",
    category: "Birthday Cakes",
    price: 689,
    originalPrice: 689,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Customizable birthday photo cake topped with your favorite celebration memory.",
    description: "Make birthdays unforgettable with this delicious cream cake, designed to display a personalized celebration photo on top.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Milestone", "Celebration"],
    tags: ["Photo Cake", "Customizable", "Birthday Special", "Memories"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "rasmalai-pista-whipped-cream-cake",
    name: "Rasmalai Pista Whipped Cream Cake",
    category: "Birthday Cakes",
    price: 675,
    originalPrice: 675,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Decadent Indian fusion sponge soaked in cardamom milk and crushed pistachios.",
    description: "Delicious fusion cake bringing together authentic rasmalai flavors, airy whipped cream, aromatic cardamom essence, and toasted pistachios.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Festive", "Family Gathering"],
    tags: ["Rasmalai", "Pista", "Whipped Cream", "Fusion Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "red-velvet-coffee-drip-cream-cake",
    name: "Red Velvet Coffee Drip Cream Cake",
    category: "Birthday Cakes",
    price: 599,
    originalPrice: 599,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Velvety red sponge paired with rich coffee drizzle and smooth cream frosting.",
    description: "A contemporary birthday favorite combining deep red velvet crumb, aromatic coffee drip, and velvety smooth cream layers.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Special Occasion"],
    tags: ["Red Velvet", "Coffee Drip", "Designer Cake", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "jungle-paradise-theme-cake",
    name: "Jungle Paradise Theme Cake",
    category: "Birthday Cakes",
    price: 1499,
    originalPrice: 1499,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Exciting jungle safari theme cake adorned with vibrant wildlife accents.",
    description: "An adventurous safari-themed birthday cake crafted with playful animal figures, lush greenery accents, and moist delicious sponge layers.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Kids Birthday", "Theme Party", "Adventure"],
    tags: ["Jungle Theme", "Safari Cake", "Kids Birthday", "Designer"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "barbie-floral-gown-cake",
    name: "Barbie Floral Gown Cake",
    category: "Birthday Cakes",
    price: 1569,
    originalPrice: 1569,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Stunning Barbie designer cake dressed in an intricate cascading floral buttercream gown.",
    description: "Grand designer birthday cake highlighting a stunning doll figure styled in an opulent handcrafted floral gown of pastel cream rosettes.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Kids Birthday", "Birthday Celebration", "Princess Party"],
    tags: ["Barbie Cake", "Floral Gown", "Designer Cake", "Theme Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "blueberry-vanilla-cake",
    name: "Blueberry Vanilla Cake",
    category: "Birthday Cakes",
    price: 599,
    originalPrice: 599,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Soft vanilla sponge layered with tangy wild blueberry compote and light frosting.",
    description: "A delightful balance of sweet aromatic vanilla sponge and tart wild blueberry reduction, enveloped in silky frosting.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Get Together", "Celebration"],
    tags: ["Blueberry", "Vanilla", "Fruit Infused", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "glazed-german-black-forest-cake",
    name: "Glazed German Black Forest Cake",
    category: "Birthday Cakes",
    price: 599,
    originalPrice: 599,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Premium German black forest cake finished with a glossy mirror chocolate glaze.",
    description: "Elevated black forest cake featuring layers of cocoa sponge, cherry infusion, whipped cream, and a shimmering chocolate mirror glaze.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Anniversary"],
    tags: ["Glazed Cake", "German Black Forest", "Mirror Glaze", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "pink-and-orange-red-velvet-cake",
    name: "Pink & Orange Red Velvet Cake",
    category: "Birthday Cakes",
    price: 689,
    originalPrice: 689,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Vibrant duo-toned red velvet cake styled with cheerful pink and sunset orange piping.",
    description: "A festive celebration cake blending rich red velvet crumb with artistic pink and orange cream swirls for bright birthday moments.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["Red Velvet", "Duo Toned", "Colourful", "Birthday Special"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "fruits-and-sprinkles-vanilla-cake",
    name: "Fruits & Sprinkles Vanilla Cake",
    category: "Birthday Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Joyful vanilla celebration cake topped with fresh fruit slices and rainbow sprinkles.",
    description: "Cheerful party cake featuring moist vanilla sponge, fresh cut seasonal fruits, and confetti sprinkles that make every birthday special.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Kids Party", "Celebration"],
    tags: ["Vanilla Cake", "Sprinkles", "Fresh Fruit", "Party Special"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "butterscotch-crunch-designer-cake",
    name: "Butterscotch Crunch Designer Cake",
    category: "Birthday Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Artistically crafted butterscotch cake embellished with crunchy caramel praline.",
    description: "A designer twist on classic butterscotch, featuring gourmet caramel drizzle, whipped buttercream, and crunchy caramelized nougat.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Anniversary"],
    tags: ["Butterscotch", "Designer Cake", "Caramel Crunch", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "love-n-rose-cake",
    name: "Love N Rose Cake",
    category: "Birthday Cakes",
    price: 675,
    originalPrice: 675,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Charming floral celebration cake designed with delicate rose motifs.",
    description: "Express love and celebration with this handcrafted sponge cake adorned with gentle rose piping and silky smooth cream.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Romantic", "Celebration"],
    tags: ["Love Cake", "Rose Theme", "Romantic", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "red-velvet-elegance-cake",
    name: "Red Velvet Elegance Cake",
    category: "Birthday Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Sophisticated red velvet cake finished with minimalist cream rosettes and velvet crumb.",
    description: "Timeless and elegant red velvet sponge layered with smooth cream cheese frosting and fine red velvet crumbs, crafted for tasteful celebrations.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Special Gathering"],
    tags: ["Red Velvet", "Elegance", "Designer", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "tropical-pineapple-cake",
    name: "Tropical Pineapple Cake",
    category: "Birthday Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Zesty tropical pineapple sponge packed with juicy fruit compote.",
    description: "A sunshine-filled birthday cake bursting with fresh pineapple chunks, light vanilla sponge, and fluffy whipped cream.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Family Celebration", "Summer Party"],
    tags: ["Pineapple", "Tropical", "Fresh Fruit", "Birthday Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "floral-drip-cake",
    name: "Floral Drip Cake",
    category: "Birthday Cakes",
    price: 1189,
    originalPrice: 1189,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Modern artisanal drip cake adorned with delicate edible floral decor.",
    description: "A chic contemporary celebration cake featuring silky smooth pastel frosting, a rich glossy ganache drip, and handcrafted floral accents.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Grand Celebration", "Anniversary"],
    tags: ["Drip Cake", "Floral", "Modern Designer", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "blueberry-heaven-pull-me-up-cake",
    name: "Blueberry Heaven Pull Me Up Cake",
    category: "Birthday Cakes",
    price: 1379,
    originalPrice: 1379,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Interactive pull-me-up cake releasing a decadent cascade of creamy blueberry sauce.",
    description: "An exhilarating party highlight featuring a moist sponge tower that gets engulfed in an irresistible tsunami of blueberry cream when the wrap is pulled up.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Interactive Celebration", "Party Highlight"],
    tags: ["Pull Me Up", "Blueberry", "Tsunami Cake", "Interactive Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },

  // ----------------------------------------------------
  // CATEGORY 2: Chocolate Cakes (19 items)
  // ----------------------------------------------------
  {
    id: "rich-chocolate-truffle-cake",
    name: "Rich Chocolate Truffle Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Indulgent Dutch cocoa sponge smothered in silky dark chocolate truffle ganache.",
    description: "A decadent delight for chocolate purists, featuring moist chocolate sponge enveloped in luscious melted truffle ganache.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Chocolate Lovers"],
    tags: ["Chocolate Truffle", "Rich Chocolate", "Dark Ganache", "Best Seller"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.455Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "choco-chip-truffle-cake",
    name: "Choco Chip Truffle Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Silky chocolate truffle cake loaded with crunchy semi-sweet chocolate chips.",
    description: "Soft chocolate layers smothered in rich truffle ganache and generously studded with crunchy dark chocolate chips for double indulgence.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["Choco Chip", "Truffle Cake", "Chocolate", "Crunchy"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "chocolate-vanilla-half-and-half-cake",
    name: "Chocolate Vanilla Half & Half Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "The best of both worlds with half rich chocolate ganache and half silky vanilla cream.",
    description: "Can't choose between chocolate and vanilla? Enjoy this duo cake with one side coated in rich chocolate truffle and the other in smooth vanilla cream.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Family Party"],
    tags: ["Half and Half", "Chocolate Vanilla", "Duo Cake", "Popular"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "roll-up-chocolate-truffle-cake",
    name: "Roll Up Chocolate Truffle Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Artistic chocolate truffle cake crowned with delicate chocolate curls and roll-ups.",
    description: "Deep chocolate sponge finished with velvety truffle frosting and garnished with handcrafted chocolate roll-ups for a luxurious texture.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Celebration"],
    tags: ["Chocolate Roll Up", "Truffle", "Artisanal", "Chocolate Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "choco-truffle-cake-made-with-kitkat",
    name: "Choco Truffle Cake Made With KitKat",
    category: "Chocolate Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Rich chocolate truffle cake bordered with crunchy KitKat wafer bars.",
    description: "An irresistible chocolate fantasy surrounded by crisp KitKat wafer fingers and crowned with smooth chocolate truffle ganache.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Cheat Day"],
    tags: ["KitKat Cake", "Choco Truffle", "Wafer Crunch", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "belgian-chocolate-cake",
    name: "Belgian Chocolate Cake",
    category: "Chocolate Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Gourmet cake crafted with authentic rich Belgian dark chocolate couverture.",
    description: "Experience European luxury with this premium cake layered with deep Belgian chocolate mousse and a velvety dark chocolate glaze.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Gourmet Celebration", "Anniversary"],
    tags: ["Belgian Chocolate", "Couverture", "Gourmet", "Dark Chocolate"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "chocolate-ganache-truffle-cake",
    name: "Chocolate Ganache Truffle Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Classic dark chocolate sponge coated in glossy warm chocolate ganache.",
    description: "Melt-in-mouth cocoa sponge generously drenched with slow-cooked chocolate ganache and finished with cocoa dusting.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Chocolate Craving"],
    tags: ["Chocolate Ganache", "Truffle", "Classic Chocolate", "Rich Cocoa"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "choco-dream-cake",
    name: "Choco Dream Cake",
    category: "Chocolate Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Multi-layered chocolate sensation topped with a crackable chocolate shell.",
    description: "A viral trending dessert featuring multiple luscious layers of chocolate sponge, gooey mousse, rich ganache, and a dusting of pure cocoa.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Celebration", "Indulgence"],
    tags: ["Dream Cake", "Chocolate Fantasy", "Gooey Ganache", "Trending"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "velvet-chocolate-truffle-cake",
    name: "Velvet Chocolate Truffle Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Silky chocolate sponge infused with smooth velvety truffle frosting.",
    description: "Rich chocolate layers crafted to velvety perfection, coated in smooth truffle cream and finished with elegant chocolate details.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["Velvet Chocolate", "Truffle Cake", "Silky Ganache", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "chocolate-snicker-cake",
    name: "Chocolate Snicker Cake",
    category: "Chocolate Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Decadent chocolate cake loaded with gooey caramel and roasted peanuts.",
    description: "Inspired by the iconic candy bar, this cake blends rich chocolate sponge, luscious caramel drizzle, and crunchy roasted peanuts.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Cheat Day"],
    tags: ["Snicker Cake", "Caramel Peanut", "Chocolate", "Crunchy"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "rosey-heart-choco-truffle-cake",
    name: "Rosey Heart Choco Truffle Cake",
    category: "Chocolate Cakes",
    price: 749,
    originalPrice: 749,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Heart-shaped chocolate truffle cake finished with romantic chocolate rosette piping.",
    description: "Deep chocolate truffle cake crafted in a romantic heart silhouette and garnished with delicate chocolate rosettes for your loved one.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Anniversary", "Birthday", "Romantic Celebration"],
    tags: ["Heart Cake", "Choco Truffle", "Romantic", "Rosette"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "marble-chocolate-cake",
    name: "Marble Chocolate Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Artistic swirl cake combining rich cocoa and sweet vanilla ribbons.",
    description: "A delightful union of rich chocolate and fragrant vanilla swirled together into a beautiful marble pattern and glazed with chocolate drizzle.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Tea Time", "Celebration"],
    tags: ["Marble Cake", "Chocolate Vanilla Swirl", "Classic", "Celebration"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "ferrero-infused-celebration-cake",
    name: "Ferrero Infused Celebration Cake",
    category: "Chocolate Cakes",
    price: 779,
    originalPrice: 779,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Hazelnut chocolate cake infused with crushed Ferrero rocher and nut praline.",
    description: "A lavish celebration cake combining roasted hazelnut cream, crunchy wafer bits, rich cocoa sponge, and Ferrero-inspired chocolate coating.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Luxury Celebration"],
    tags: ["Ferrero Cake", "Hazelnut", "Praline", "Luxury Chocolate"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "hearts-of-love-chocolate-cake",
    name: "Hearts Of Love Chocolate Cake",
    category: "Chocolate Cakes",
    price: 749,
    originalPrice: 749,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Passionate chocolate cake decorated with handcrafted chocolate hearts.",
    description: "A romantic chocolate creation with layers of dark truffle sponge and sweet decorative chocolate heart toppers.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Valentine"],
    tags: ["Hearts Of Love", "Chocolate Cake", "Romantic", "Truffle"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "choco-vanilla-delight-cake",
    name: "Choco Vanilla Delight Cake",
    category: "Chocolate Cakes",
    price: 549,
    originalPrice: 549,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Harmonious layers of chocolate fudge sponge and smooth vanilla buttercream.",
    description: "A delightful treat pairing moist chocolate fudge sponge with light vanilla cream frosting and chocolate drizzle.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party", "Celebration"],
    tags: ["Choco Vanilla", "Delight Cake", "Celebration", "Chocolate"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "ferrero-rocher-pinata-cake",
    name: "Ferrero Rocher Pinata Cake",
    category: "Chocolate Cakes",
    price: 1289,
    originalPrice: 1289,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Exciting smashable chocolate pinata shell hiding rich hazelnut chocolates inside.",
    description: "An interactive party sensation! Smash open the premium chocolate dome shell to reveal decadent chocolates, treats, and sponge inside.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Party Surprise", "Smash Cake"],
    tags: ["Pinata Cake", "Ferrero Rocher", "Smash Cake", "Party Surprise"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "happy-birthday-chocolate-photo-cake",
    name: "Happy Birthday Chocolate Photo Cake",
    category: "Chocolate Cakes",
    price: 689,
    originalPrice: 689,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Rich chocolate truffle birthday cake featuring a personalized edible photo topper.",
    description: "Celebrate with rich chocolate truffle indulgence topped with a customized celebration photo frame for a personalized birthday surprise.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Milestone", "Surprise"],
    tags: ["Photo Cake", "Chocolate Truffle", "Customized", "Birthday"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "chocolate-truffle-fresh-fruit-cake",
    name: "Chocolate Truffle Fresh Fruit Cake",
    category: "Chocolate Cakes",
    price: 799,
    originalPrice: 799,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Luxurious blend of dark chocolate truffle ganache topped with fresh juicy fruits.",
    description: "Indulge in rich dark chocolate truffle sponge crowned with an assortment of vibrant fresh seasonal fruits for a burst of fresh flavor.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Anniversary", "Celebration"],
    tags: ["Chocolate Fruit", "Truffle Cake", "Fresh Fruit", "Gourmet"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "french-la-opera-coffee-choco-cake",
    name: "French La Opera Coffee Choco Cake",
    category: "Chocolate Cakes",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Classic French-style layered almond sponge, rich coffee buttercream, and dark chocolate ganache.",
    description: "An exquisite French patisserie classic featuring delicate almond sponge infused with espresso syrup, layered with coffee cream and chocolate glaze.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Gourmet Gathering", "Celebration"],
    tags: ["Opera Cake", "French Pastry", "Coffee Chocolate", "Gourmet"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },

  // ----------------------------------------------------
  // CATEGORY 3: Pastries (3 items)
  // ----------------------------------------------------
  {
    id: "happy-birthday-chocolate-pastries",
    name: "Happy Birthday Chocolate Pastries",
    category: "Pastries",
    price: 199,
    originalPrice: 199,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Individual celebratory chocolate truffle pastry slice with festive birthday plaque.",
    description: "Fresh individual chocolate truffle pastry slice layered with smooth cocoa cream and topped with a Happy Birthday chocolate topper.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Quick Celebration", "Solo Treat"],
    tags: ["Chocolate Pastry", "Birthday Pastry", "Single Serve", "Fresh Baked"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "classic-chocolate-truffle-pastry",
    name: "Classic Chocolate Truffle Pastry",
    category: "Pastries",
    price: 99,
    originalPrice: 99,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Quick personal slice of decadent dark chocolate truffle cake.",
    description: "A delightful single-portion pastry packed with rich cocoa sponge and silky chocolate ganache for your instant sweet craving.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Tea Time", "Snack", "Sweet Craving"],
    tags: ["Truffle Pastry", "Chocolate Slice", "Pocket Friendly", "Quick Bite"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "assorted-pastry-box",
    name: "Assorted Pastry Box",
    category: "Pastries",
    price: 199,
    originalPrice: 199,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Curated collection of freshly crafted pastries in customizable box sizes (₹199–₹1999).",
    description: "A delectable selection of our finest artisanal pastry slices including chocolate truffle, fruit, and butterscotch. Available in boxes ranging from ₹199 to ₹1999.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Party", "Family Treat", "Gifting", "Office Celebration"],
    tags: ["Pastry Box", "Assorted Pastries", "Party Pack", "Gifting"],
    variants: ["Pack of 2 (₹199)", "Pack of 4 (₹389)", "Pack of 6 (₹549)", "Indulgence Box of 12 (₹999)", "Grand Party Feast (₹1999)"],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },

  // ----------------------------------------------------
  // CATEGORY 4: Beer Theme Cakes (9 items)
  // ----------------------------------------------------
  {
    id: "fondant-theme-beer-mug-cake",
    name: "Fondant Theme Beer Mug Cake",
    category: "Beer Theme Cakes",
    price: 2379,
    originalPrice: 2379,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Elaborate 3D handcrafted fondant beer mug cake complete with frothy foam details.",
    description: "A stunning centerpiece shaped like an overflowing mug of chilled beer with realistic froth, golden brew finish, and rich delicious cake inside.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Bachelor Party", "Birthday", "Guys Night", "Celebration"],
    tags: ["Beer Mug Cake", "Fondant Cake", "3D Theme Cake", "Bachelor Party"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "no-more-single-beer-bachelor-cake",
    name: "No More Single Beer Bachelor Cake",
    category: "Beer Theme Cakes",
    price: 1699,
    originalPrice: 1699,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Fun bachelor party celebration cake celebrating the groom's milestone with beer accents.",
    description: "The ultimate celebration cake for bachelor parties and groom celebrations, styled with playful bachelor motifs and cool beer theme decor.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Bachelor Party", "Groom To Be", "Bachelors Celebration"],
    tags: ["Bachelor Cake", "No More Single", "Beer Theme", "Groom Party"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "beer-love-theme-cake",
    name: "Beer Love Theme Cake",
    category: "Beer Theme Cakes",
    price: 1469,
    originalPrice: 1469,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Creative celebration cake designed for true beer enthusiasts and party lovers.",
    description: "Showcase love for the brew with this custom-styled beer theme cake featuring beer bottle motifs, foam effects, and moist sponge.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Bachelors", "Party Night"],
    tags: ["Beer Love", "Theme Cake", "Party Cake", "Brew Theme"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "blue-label-whiskey-theme-cake",
    name: "Blue Label Whiskey Theme Cake",
    category: "Beer Theme Cakes",
    price: 1239,
    originalPrice: 1239,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Sophisticated celebration cake inspired by iconic luxury blue label whiskey aesthetics.",
    description: "A refined celebration cake tailored for whiskey connoisseurs with deep blue fondant details, gold trims, and luxury label styling.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Milestone Birthday", "Gentlemens Party", "Celebration"],
    tags: ["Whiskey Cake", "Blue Label", "Luxury Theme", "Gentlemen Party"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "cheers-to-beer-celebration-cake",
    name: "Cheers To Beer Celebration Cake",
    category: "Beer Theme Cakes",
    price: 1379,
    originalPrice: 1379,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Vibrant party cake with clinking beer mug toppers and celebratory cheers styling.",
    description: "Raise a toast with this lively celebration cake designed with foaming beer mugs and vibrant party colors for cheerful gatherings.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Cheers Party", "Get Together"],
    tags: ["Cheers Cake", "Beer Theme", "Party Celebration", "Toast"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "tuborg-beer-themed-cake",
    name: "Tuborg Beer Themed Cake",
    category: "Beer Theme Cakes",
    price: 1379,
    originalPrice: 1379,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Green and gold themed celebration cake showcasing iconic Tuborg beer styling.",
    description: "A tribute cake for Tuborg lovers featuring the signature green and gold bottle aesthetic, foaming details, and rich delicious sponge.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Weekend Party", "Celebration"],
    tags: ["Tuborg Theme", "Beer Cake", "Bottle Theme", "Party Special"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "cheers-beer-mug-cake",
    name: "Cheers Beer Mug Cake",
    category: "Beer Theme Cakes",
    price: 1469,
    originalPrice: 1469,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Custom sculpted beer mug cake with golden brew color and cascading froth.",
    description: "Celebrate high spirits with this handcrafted beer mug cake featuring rich sponge layers, caramel or cocoa filling, and fluffy white froth.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Bachelor Party", "Weekend Bash"],
    tags: ["Cheers Mug", "Beer Mug Cake", "Sculpted Cake", "Party"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "cheers-to-forty-beer-cake",
    name: "Cheers To Forty Beer Cake",
    category: "Beer Theme Cakes",
    price: 1469,
    originalPrice: 1469,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Milestone 40th birthday celebration cake paired with playful cheers and beer accents.",
    description: "Celebrate stepping into forty with style! Features custom 'Cheers to 40' birthday artwork and beer-inspired festive decorations.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["40th Birthday", "Milestone Celebration", "Party"],
    tags: ["Cheers To Forty", "40th Birthday", "Milestone", "Beer Theme"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "the-heineken-beer-theme-cake",
    name: "The Heineken Beer Theme Cake",
    category: "Beer Theme Cakes",
    price: 1649,
    originalPrice: 1649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Distinctive green star Heineken bottle theme celebration cake.",
    description: "Stylishly designed with the iconic green bottle aesthetic, signature red star, and frothy brew accents over moist premium cake layers.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Birthday", "Bachelor Party", "Party Night"],
    tags: ["Heineken Cake", "Beer Bottle Cake", "Theme Cake", "Party"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },

  // ----------------------------------------------------
  // CATEGORY 5: Desserts (11 items)
  // ----------------------------------------------------
  {
    id: "blueberry-cheesecake",
    name: "Blueberry Cheesecake",
    category: "Desserts",
    price: 779,
    originalPrice: 779,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "New York style baked cheesecake topped with thick, luscious blueberry compote.",
    description: "Velvety smooth cream cheese filling baked over a buttery biscuit crust and topped with tangy wild blueberry glaze.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Dessert Night", "Special Treat", "Celebration"],
    tags: ["Cheesecake", "Blueberry", "Baked Cheesecake", "Gourmet Dessert"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "red-velvet-jar-cake",
    name: "Red Velvet Jar Cake",
    category: "Desserts",
    price: 139,
    originalPrice: 139,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Individual glass jar packed with layers of red velvet crumb and cream cheese frosting.",
    description: "A delightful portable treat layering soft red velvet sponge and sweet cream cheese mousse inside a reusable dessert jar.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Sweet Craving", "Gift", "Solo Treat"],
    tags: ["Jar Cake", "Red Velvet", "Dessert Jar", "Single Serve"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "trio-mousse-cake",
    name: "Trio Mousse Cake",
    category: "Desserts",
    price: 649,
    originalPrice: 649,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Triple-layered chilled mousse dessert featuring dark, milk, and white chocolate layers.",
    description: "An ethereal dessert combining three silky tiers of dark, milk, and white chocolate mousse over a thin cocoa sponge base.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Celebration", "Dinner Party", "Chocolate Dessert"],
    tags: ["Trio Mousse", "Triple Chocolate", "Mousse Cake", "Chilled Dessert"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "pink-almond-rocher-dessert",
    name: "Pink Almond Rocher Dessert",
    category: "Desserts",
    price: 219,
    originalPrice: 219,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Gourmet nutty dessert bowl layered with pink chocolate and roasted almond rocher.",
    description: "A trendy artisanal dessert featuring crunchy roasted almonds enveloped in delicate pink chocolate cream and velvety mousse.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Indulgence", "After Dinner Dessert", "Sweet Craving"],
    tags: ["Almond Rocher", "Pink Chocolate", "Artisanal Dessert", "Nutty"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "chocolate-mud-jar-cake",
    name: "Chocolate Mud Jar Cake",
    category: "Desserts",
    price: 139,
    originalPrice: 139,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Gooey chocolate mud cake layers and dense chocolate ganache in a grab-and-go jar.",
    description: "For serious chocolate cravings — intensely rich chocolate mud sponge packed tightly with melted chocolate fudge in a handy jar.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Snack", "Late Night Craving", "Dessert Treat"],
    tags: ["Mud Jar Cake", "Chocolate Fudge", "Dessert Jar", "Rich Chocolate"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "choco-mousse-verrine-cup-no-added-sugar",
    name: "Choco Mousse Verrine Cup No Added Sugar",
    category: "Desserts",
    price: 209,
    originalPrice: 209,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Smooth and airy dark chocolate mousse in an elegant verrine cup with No Added Sugar.",
    description: "Guilt-free indulgence featuring airy cocoa mousse crafted with No Added Sugar, served in a stylish French verrine cup.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Guilt Free", "Diet Friendly", "Daily Treat"],
    tags: ["No Added Sugar", "Choco Mousse", "Verrine Cup", "Healthier Choice"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "mango-shape-dessert",
    name: "Mango Shape Dessert",
    category: "Desserts",
    price: 249,
    originalPrice: 249,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Hyper-realistic mango-shaped handcrafted mousse dessert with luscious alphonso puree center.",
    description: "A stunning trompe-l'œil pastry dessert sculpted into a real Alphonso mango, filled with delicate fruit mousse and tangy mango coulis.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Gourmet Treat", "Dinner Party", "Unique Dessert"],
    tags: ["Mango Shape", "Realistic Dessert", "Alphonso", "French Patisserie"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "kunafa-chocolate-tub",
    name: "Kunafa Chocolate Tub",
    category: "Desserts",
    price: 269,
    originalPrice: 269,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Crispy roasted pistachio kataifi pastry layered with molten chocolate ganache in a tub.",
    description: "The sensational Dubai-style dessert featuring crunchy buttery kunafa kataifi, rich pistachio cream, and thick milk chocolate.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Trending Treat", "Dessert Night", "Gourmet Craving"],
    tags: ["Kunafa Chocolate", "Dubai Chocolate", "Pistachio Kunafa", "Viral Dessert"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "dark-chocolate-scoop-cookie",
    name: "Dark Chocolate Scoop Cookie",
    category: "Desserts",
    price: 209,
    originalPrice: 209,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Chunky, warm-baked giant dark chocolate scoop cookie with a gooey molten center.",
    description: "Thick American-style bakery cookie baked to crispy outer perfection with a rich, molten dark chocolate center.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Coffee Companion", "Sweet Snack", "Indulgence"],
    tags: ["Scoop Cookie", "Dark Chocolate", "Bakery Cookie", "Gooey Center"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.456Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "assorted-cupcake-indulgence-box",
    name: "Assorted Cupcake Indulgence Box",
    category: "Desserts",
    price: 169,
    originalPrice: 169,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Delicious box of assorted fresh cream cupcakes in customizable pack sizes (₹169–₹999).",
    description: "A delightful box of gourmet cupcakes featuring assorted flavors and handcrafted cream swirls. Available in packs ranging from ₹169 to ₹999.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Party Snack", "Kids Treat", "Office Party", "Gifting"],
    tags: ["Cupcake Box", "Assorted Cupcakes", "Indulgence Box", "Sweet Treat"],
    variants: ["Pack of 2 (₹169)", "Pack of 4 (₹329)", "Pack of 6 (₹479)", "Deluxe Box of 12 (₹999)"],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  },
  {
    id: "blueberry-jar-cake",
    name: "Blueberry Jar Cake",
    category: "Desserts",
    price: 139,
    originalPrice: 139,
    discount: 0,
    rating: 0,
    reviewCount: 0,
    image: "",
    gallery: [],
    deliveryTime: "Within 12 hours",
    inStock: true,
    shortDescription: "Fresh vanilla sponge and sweet blueberry compote layered beautifully in a single-serve jar.",
    description: "Layers of moist vanilla cake, tangy blueberry reduction, and light whipped cream packed into a portable single-serve dessert jar.",
    ingredients: [],
    allergens: [],
    storageInstructions: "Store in a cool, dry place or refrigerate.",
    occasions: ["Snack", "Sweet Craving", "Gift"],
    tags: ["Blueberry Jar", "Fruit Dessert", "Single Portion", "Jar Cake"],
    variants: [],
    createdAt: "2026-09-05T18:01:02.457Z",
    updatedAt: "2026-09-06T00:00:00.000Z"
  }
];

async function main() {
  console.log('Writing categorized products to products.json...');
  fs.writeFileSync(
    path.join(__dirname, '../src/data/db/products.json'),
    JSON.stringify(categorizedProducts, null, 2),
    'utf8'
  );
  console.log(`Saved ${categorizedProducts.length} categorized products to products.json.`);

  // Connect to PostgreSQL and update/insert each product
  const connectionString = process.env.POSTGRES_URL || process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/velmora';
  const pool = new Pool({ connectionString });

  try {
    const client = await pool.connect();
    console.log('Connected to PostgreSQL.');

    // Ensure shortDescription column exists if table is present
    await client.query(`
      ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "shortDescription" TEXT;
      ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "tags" JSONB DEFAULT '[]'::jsonb;
    `).catch(err => console.warn('Column add warning (non-fatal):', err.message));

    // Upsert each of the 67 products into PostgreSQL
    for (const p of categorizedProducts) {
      await client.query(`
        INSERT INTO "products" (
          id, name, description, "shortDescription", price, "originalPrice", discount, image, gallery,
          category, "subCategory", rating, "reviewCount", "inStock", "deliveryTime",
          ingredients, allergens, "storageInstructions", occasions, variants, tags, "createdAt", "updatedAt"
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
        ) ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          "shortDescription" = EXCLUDED."shortDescription",
          price = EXCLUDED.price,
          "originalPrice" = EXCLUDED."originalPrice",
          discount = EXCLUDED.discount,
          category = EXCLUDED.category,
          "subCategory" = EXCLUDED."subCategory",
          "deliveryTime" = EXCLUDED."deliveryTime",
          "storageInstructions" = EXCLUDED."storageInstructions",
          occasions = EXCLUDED.occasions,
          variants = EXCLUDED.variants,
          tags = EXCLUDED.tags,
          "updatedAt" = EXCLUDED."updatedAt"
      `, [
        p.id, p.name, p.description || '', p.shortDescription || '', p.price, p.originalPrice || p.price, p.discount || 0,
        p.image || '', JSON.stringify(p.gallery || []), p.category, p.subCategory || null,
        p.rating || 0, p.reviewCount || 0, p.inStock !== undefined ? p.inStock : true, p.deliveryTime || 'Within 12 hours',
        JSON.stringify(p.ingredients || []), JSON.stringify(p.allergens || []), p.storageInstructions || '',
        JSON.stringify(p.occasions || []), JSON.stringify(p.variants || []), JSON.stringify(p.tags || []),
        p.createdAt || new Date().toISOString(), p.updatedAt || new Date().toISOString()
      ]);
    }

    const countRes = await client.query('SELECT count(*) FROM "products"');
    console.log(`PostgreSQL products table now has ${countRes.rows[0]?.count} products.`);

    const catCounts = await client.query('SELECT category, count(*) FROM "products" GROUP BY category ORDER BY count DESC');
    console.log('Category distribution in PostgreSQL:');
    catCounts.rows.forEach(r => console.log(` - ${r.category}: ${r.count}`));

    client.release();
  } catch (err) {
    console.error('PostgreSQL sync error:', err);
  } finally {
    await pool.end().catch(() => {});
  }
}

main();
